version: '3'

services:
  product-service:
    image: php:7.4-apache
    volumes:
      - ./product:/var/www/html
    ports:
      - 5001:80

  website:
    image: php:7.4-apache
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 80:80
    depends_on:
      - product-service