version: '3'

services:
  product-service:
    
    build: ./product
    container_name: product
    volumes:
      - ./product:/var/www/html
    ports:
      - 8101:80

  website:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 80:80
    depends_on:
      - product-service