

FROM php:7.4-apache

RUN apt-get update && apt-get upgrade -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli \
    && a2enmod headers \
    && sed -ri -e 's/^([ \t]*)(<\/VirtualHost>)/\1\tHeader set Access-Control-Allow-Origin "*"\n\1\2/g' /etc/apache2/sites-available/*.conf

# COPY index.php /var/www/html
# COPY .htaccess /var/www/html

# RUN a2enmod headers

# RUN apachectl -t
# RUN apachectl -k graceful

# RUN a2enmod headers









EXPOSE 80