

FROM php:7.4-apache

RUN apt-get update && apt-get upgrade -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY index.php /var/www/html
COPY .htaccess /var/www/html

RUN a2enmod headers

RUN apachectl -t
RUN apachectl -k graceful
RUN apachectl -k graceful
RUN a2enmod headers









EXPOSE 80